// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback:                       1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    x_project_funding
    (
        init => init
        upgrade => upgrade
        init_first_x_project => init_first_x_project
        deployXProject => deploy_x_project
        fundProject => fund_project
        unlockXht => unlock_xht
        getXhtID => xht
        registerLkXht => register_lk_xht_token
        set_x_project_token => set_x_project_token
        claim_x_project_tokens => claim_x_project_tokens
        getXProjectTokenID => x_project_token_id
        getXProjectAddress => x_project_address
        getLkXhtID => lk_xht
    )
}

multiversx_sc_wasm_adapter::async_callback! { x_project_funding }
