[package]
name = "coinbase-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.coinbase]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.50.1"
default-features = false

[workspace]
